name: "Resolve Runtime Defaults"
description: "Resolves runtime/toolchain defaults from vendored runtime-matrix.yml"

inputs:
  runtime_name:
    description: "One of: node|python|java|dotnet|go"
    required: true
  runtime_version:
    description: "Optional override (e.g., 20.x, 3.12, 21, 8.0.x, 1.22.x)"
    required: false
    default: ""

outputs:
  runtime_version:
    description: "Resolved runtime version (override or matrix default)"
  support_status:
    description: "supported|experimental|planned"
  package_manager_default:
    description: "Default package manager per runtime"
  build_tool_default:
    description: "Default build tool per runtime"

runs:
  using: "node20"
  main: "dist/index.js"
